#!/usr/bin/env perl -T
# $Id$

use strict;
use Getopt::Std;

$Getopt::Std::STANDARD_HELP_VERSION = 1;
our $VERSION = 0.1;

my %options = () ;
getopts("hf:nvV", \%options);

if ($options{h}) {
    VERSION_MESSAGE();
    HELP_MESSAGE();
    exit 0;
}

if ($options{V}) {
    VERSION_MESSAGE();
    exit 0;
}

if (!$options{f} and @ARGV == 0) {
    VERSION_MESSAGE();
    HELP_MESSAGE();
    exit 1;
}

#die "Need to run as root.\n" unless ($< == 0);

exit 0;

sub HELP_MESSAGE {
    print "Usage: rawsuserdel [-hnvV] [-f file | username...]\n";
    print "   -h, --help     Prints this message and exits\n";
    print "   -f             Use file as input\n";
    print "   -n             Test mode\n";
    print "   -v             Be verbose\n";
    print "   -V, --version  Prints version message and exits\n";
}

sub VERSION_MESSAGE {
    print "rawsuserdel version $VERSION\n";
}

# vi: set tabstop=4 shiftwidth=4 expandtab si ai nu:
